// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backlaba13._1.Model;

#nullable disable

namespace backlaba13._1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backlaba13._1.Cards", b =>
                {
                    b.Property<int>("balance")
                        .HasColumnType("integer");

                    b.Property<string>("cvc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_card")
                        .HasColumnType("integer");

                    b.Property<int>("id_person")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("backlaba13._1.Model.Auth", b =>
                {
                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_user")
                        .HasColumnType("integer");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Auth");
                });

            modelBuilder.Entity("backlaba13._1.Model.Users", b =>
                {
                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_users")
                        .HasColumnType("integer");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backlaba13._1.Story", b =>
                {
                    b.Property<int>("id_transfer")
                        .HasColumnType("integer");

                    b.Property<int>("id_user")
                        .HasColumnType("integer");

                    b.Property<string>("kyda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("otkyda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Story");
                });
#pragma warning restore 612, 618
        }
    }
}
